import { NextRequest, NextResponse } from 'next/server';

// Route Handler chạy server-side. Ưu tiên INTERNAL_API_URL (localhost) để skip Cloudflare round-trip.
// Fallback NEXT_PUBLIC_API_URL khi chưa cấu hình.
const API_BASE = process.env.INTERNAL_API_URL || process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3010/api/v1';

/** Access token cookie lifetime (1h - sync với BE JWT signOptions). */
const ACCESS_COOKIE_MAX_AGE = 60 * 60;
/** Refresh token cookie lifetime (7d). */
const REFRESH_COOKIE_MAX_AGE = 7 * 24 * 60 * 60;

/**
 * In-memory mutex cho refresh-token rotation. Khi nhiều request 401 cùng lúc (page có
 * 5-7 endpoint song song), tất cả share cùng 1 promise refresh - tránh race condition
 * khiến BE invalidate refresh token cũ giữa chừng và đẩy user logout oan.
 *
 * Map key = giá trị refresh token raw (random 32 bytes hex - duy nhất per session).
 * Sau khi promise settle (success/fail), xoá key để tránh giữ promise stale.
 *
 * Lưu ý: in-memory Map chỉ work trong same Next.js process. Khi scale nhiều
 * instance, cần chuyển sang shared store (vd Redis).
 */
interface RefreshResult {
  ok: boolean;
  accessToken?: string;
  refreshToken?: string;
  data?: unknown;
  status?: number;
}

const refreshInflight = new Map<string, Promise<RefreshResult>>();

async function doRefresh(refreshToken: string): Promise<RefreshResult> {
  try {
    const refreshRes = await fetch(`${API_BASE}/auth/refresh`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ refreshToken }),
    });
    const data = await refreshRes.json().catch(() => ({}));
    if (!refreshRes.ok) {
      return { ok: false, status: refreshRes.status, data };
    }
    return {
      ok: true,
      accessToken: data.data?.accessToken,
      refreshToken: data.data?.refreshToken,
      data,
    };
  } catch {
    return { ok: false, status: 502 };
  }
}

/**
 * Lấy hoặc tạo promise refresh chung cho 1 refresh token. Concurrent callers cùng token
 * sẽ share kết quả. Promise được xoá khỏi map sau khi settle.
 */
function getOrCreateRefreshPromise(refreshToken: string): Promise<RefreshResult> {
  const existing = refreshInflight.get(refreshToken);
  if (existing) return existing;
  const promise = doRefresh(refreshToken).finally(() => {
    refreshInflight.delete(refreshToken);
  });
  refreshInflight.set(refreshToken, promise);
  return promise;
}

function setAuthCookies(response: NextResponse, accessToken: string, refreshToken: string) {
  const isProd = process.env.NODE_ENV === 'production';
  response.cookies.set('access_token', accessToken, {
    httpOnly: true, secure: isProd, sameSite: 'lax', path: '/', maxAge: ACCESS_COOKIE_MAX_AGE,
  });
  response.cookies.set('refresh_token', refreshToken, {
    httpOnly: true, secure: isProd, sameSite: 'lax', path: '/', maxAge: REFRESH_COOKIE_MAX_AGE,
  });
}

function clearAuthCookies(response: NextResponse) {
  response.cookies.set('access_token', '', { path: '/', maxAge: 0 });
  response.cookies.set('refresh_token', '', { path: '/', maxAge: 0 });
}

/**
 * API proxy: forwards client-side requests to NestJS API with auth token from cookie.
 * Solves cross-origin cookie issue (cookie set on :3011, API on :3010).
 *
 * Khi BE trả 401, proxy thử refresh (share promise qua mutex) rồi retry request gốc.
 */
export async function handler(request: NextRequest, { params }: { params: Promise<{ path: string[] }> }) {
  const { path } = await params;
  const apiPath = '/' + path.join('/');
  const url = new URL(request.url);
  const queryString = url.search;

  const token = request.cookies.get('access_token')?.value;

  const headers: Record<string, string> = {};
  if (token) headers['Authorization'] = `Bearer ${token}`;

  // Forward content-type for non-GET requests
  const contentType = request.headers.get('content-type');
  if (contentType) headers['Content-Type'] = contentType;

  const fetchOptions: RequestInit = {
    method: request.method,
    headers,
  };

  // Forward body for non-GET/HEAD methods. Lưu vào biến để retry dùng lại được.
  let bodyForRetry: ArrayBuffer | string | undefined;
  if (!['GET', 'HEAD'].includes(request.method)) {
    if (contentType?.includes('multipart/form-data')) {
      // KEEP original Content-Type (already contains the boundary generated by browser).
      bodyForRetry = await request.arrayBuffer();
    } else {
      bodyForRetry = await request.text();
    }
    fetchOptions.body = bodyForRetry;
  }

  try {
    const res = await fetch(`${API_BASE}${apiPath}${queryString}`, fetchOptions);

    // Handle non-JSON responses (CSV downloads, etc.) - không retry trên 401 cho file download.
    const resContentType = res.headers.get('content-type') || '';
    if (!resContentType.includes('application/json')) {
      const body = await res.arrayBuffer();
      return new NextResponse(body, {
        status: res.status,
        headers: {
          'Content-Type': resContentType,
          ...(res.headers.get('content-disposition') ? { 'Content-Disposition': res.headers.get('content-disposition')! } : {}),
        },
      });
    }

    const data = await res.json();

    // Happy path: BE trả 2xx/4xx khác 401 -> forward nguyên xi.
    if (res.status !== 401) {
      return NextResponse.json(data, { status: res.status });
    }

    // 401 path: thử refresh qua mutex. Nếu không có refresh token thì clear cookies luôn.
    const refreshToken = request.cookies.get('refresh_token')?.value;
    if (!refreshToken) {
      const errResponse = NextResponse.json(data, { status: 401 });
      clearAuthCookies(errResponse);
      return errResponse;
    }

    const refreshResult = await getOrCreateRefreshPromise(refreshToken);
    if (!refreshResult.ok || !refreshResult.accessToken || !refreshResult.refreshToken) {
      // Refresh thất bại thật sự -> session hết hạn, clear cookies.
      const errResponse = NextResponse.json(data, { status: 401 });
      clearAuthCookies(errResponse);
      return errResponse;
    }

    // Retry với token mới. Reuse body đã đọc ở trên.
    headers['Authorization'] = `Bearer ${refreshResult.accessToken}`;
    const retryFetchOptions: RequestInit = { method: request.method, headers };
    if (bodyForRetry !== undefined) retryFetchOptions.body = bodyForRetry;

    const retryRes = await fetch(`${API_BASE}${apiPath}${queryString}`, retryFetchOptions);
    const retryContentType = retryRes.headers.get('content-type') || '';
    if (!retryContentType.includes('application/json')) {
      const body = await retryRes.arrayBuffer();
      const response = new NextResponse(body, {
        status: retryRes.status,
        headers: {
          'Content-Type': retryContentType,
          ...(retryRes.headers.get('content-disposition') ? { 'Content-Disposition': retryRes.headers.get('content-disposition')! } : {}),
        },
      });
      setAuthCookies(response, refreshResult.accessToken, refreshResult.refreshToken);
      return response;
    }
    const retryData = await retryRes.json();
    const response = NextResponse.json(retryData, { status: retryRes.status });
    setAuthCookies(response, refreshResult.accessToken, refreshResult.refreshToken);
    return response;
  } catch {
    return NextResponse.json({ message: 'Lỗi kết nối API server' }, { status: 502 });
  }
}

export const GET = handler;
export const POST = handler;
export const PATCH = handler;
export const PUT = handler;
export const DELETE = handler;
